// reactjs/modules/03-ignews/src/components/Post.vue
<template>
  <div class="post" >
    <h1>{{ post.title }}</h1>
    <span>by {{ post.author }}</span>
    <p>{{ post.content.preview }}</p>
    <p>...</p>
  </div>
</template>

<script>
export default {
  name: 'Post',
  props: ['post'],
  methods: {},
  components: {}
}
</script>

<style scoped lang="scss">
@import '@/styles/colors.scss';

.post {
  height: 3rem;
  width: 9rem;
  max-width: 95vw;
}

@keyframes SlideInPost {
  from {
    left: -200%;
  }

  to {
    left: 0;
  }
}
</style>

// reactjs/modules/03-ignews/src/components/post/index.tsx
import style from './style.module.scss'

interface IPost {
	id: string,
	title: string,
	content: {
		author: string,
		preview: string,
		full: string
	}
}

interface IPostProps {
	post: IPost;
	toPost: (slug: string) => void;
}

export const Post = ({ post, toPost }: IPostProps) => {
	return (
		<div
			className={style.post}
			onClick={()=>toPost(post.id)}
		>
			<h1>{post.title}</h1>
			<span>{`by: ${post.content?.author}`}</span>
			<p>{post.content?.preview}</p>
		</div>
	)
}
